### ISSUE TITLE
Is this work with this toy too?

### ISSUE THREAD

**Issue by Andrea-58** [metafetish/lovesense-rs#5]
Is this compatible with this toy too? Link: https://www.amazon.com/dp/B094JD78BD

**Comment by qdot** [comment]
First off, you'll want to use https://buttplug.io and https://github.com/buttplugio/buttplug-rs, this repo is incredibly old and needs to be archived.

In terms of support in buttplug-rs, I think it might work? There's a TON of Lovense Lush knockoffs, some of which do imitate the Lovense protocol, which we support there. I believe this is one of those, though it may have a different bluetooth name we'll have to add to the library.
